spring:
  data:
    rest:
      basePath: / #root URI for Spring Data REST
      defaultPageSize: 20 #change default number of items served in a single page
      maxPageSize: 100 #change maximum number of items in a single page
      #pageParamName: #change name of the query parameter for selecting pages
      #limitParamName: #change name of the query parameter for number of items to show in a page
      #sortParamName: #change name of the query parameter for sorting
      #defaultMediaType: #change default media type to use when none is specified
      returnBodyOnCreate: false #change if a body should be returned on creating a new entity
      returnBodyOnupdate: false #change if a body should be returned on updating an entity
  
  jpa:
    open-in-view: true
    show-sql: true
    repositories.enabled: true # if spring data repository support is enabled
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "create-drop"

  datasource:
    initialize: true # populate using data.sql
    sql-script-encoding: UTF-8 # a charset for reading SQL scripts
    separator: ; # statement separator in SQL initialization scripts
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql:users"
    username: users
    password: users
    #jndi-name: # For JNDI lookup (class, url, username & password are ignored when set)
    #max-active:100 # Advanced configuration...
    #max-idle:8
    #min-idle:8
    #initial-size:10
    #validation-query:

  logging:
    level:
      org.springframework.security: DEBUG


  oauth2:
    resource:
      id: openid
      serviceId: "user-resource"
      jwt:
        keyValue: -----BEGIN CERTIFICATE-----\nMIIDbTCCAlWgAwIBAgIEGN9bSDANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJERTEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEQMA4GA1UEChMHVW5rbm93bjEQMA4GA1UECxMHVW5rbm93bjEQMA4GA1UEAxMHVW5rbm93bjAeFw0xNTEwMDkwNTE4MzJaFw0xNjAxMDcwNTE4MzJaMGcxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYDVQQKEwdVbmtub3duMRAwDgYDVQQLEwdVbmtub3duMRAwDgYDVQQDEwdVbmtub3duMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1gkW/3z+rqFyayOWgdN9f2CCDOZqoRFm5XF5FX/t7ZaJKDFUAJFZP1XU04gWIsQWTCBiWoeozO0kko1rCOMmbC/ugyANotA1J7uDYpH1HTv5zAwVKJNlmcjNYAFTTzCHjGG/mnDrrS+fhHr+cIPNRwQHGIDLt/FAm02HKv9nV/VaXoTaVfqgbSprzlfxB3vtlh4dpn5djKJLvmZxt15DFbKwOMumRv50bbUN5oJmwdA237dXDi0BfrWqxocOoNIeQBStJL6OA//8oymSxSoiIKiWV0j0S51hfOPXJ8tLeRGfT2JmXz7Hec+bl+FsBMi6FIQAb7Zy/xQdsLk85pJzwIDAQABoyEwHzAdBgNVHQ4EFgQUIiB6OUXVgFenIspL0/R0xis8xlswDQYJKoZIhvcNAQELBQADggEBAGVLk6S2Vbx2ZMEOqPYlgqwtFp1TYZIyhDlRnN0364GRx6goT/8xPv+Gb5jvclEGrkszcLW2gNhH/Tx51sFvcpAFGjMNA6yqFZItfv2KBhSnU8bDK4rl83esvialZFP1bD57s4en+vGEvxG6hc/XERYkaRY8mGTae5xJXzRWJ2thxUoAY6B7ugL/VJp2pTHIzmtfDzuu0NCVmVD5BZu+87CRwD1lLOZQoFidqxYtzPemdWlLSF9OGYux9es7iL1sEvZtc85Rup5XNYDLmL15FsVGqcrOj52TIsu6ypRXv63oVBNB1fk/EMiBXxdqmhQ2MytXFuUODhd54N5MTV17FAU=\n-----END CERTIFICATE-----
server:
  port: 8080
