spring:
  data:
    rest:
      basePath: / #root URI for Spring Data REST
      defaultPageSize: 20 #change default number of items served in a single page
      maxPageSize: 100 #change maximum number of items in a single page
      #pageParamName: #change name of the query parameter for selecting pages
      #limitParamName: #change name of the query parameter for number of items to show in a page
      #sortParamName: #change name of the query parameter for sorting
      #defaultMediaType: #change default media type to use when none is specified
      returnBodyOnCreate: false #change if a body should be returned on creating a new entity
      returnBodyOnupdate: false #change if a body should be returned on updating an entity
  
  jpa:
    open-in-view: true
    show-sql: true
    repositories.enabled: true # if spring data repository support is enabled
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "create-drop"

  datasource:
    initialize: true # populate using data.sql
    sql-script-encoding: UTF-8 # a charset for reading SQL scripts
    separator: ; # statement separator in SQL initialization scripts
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql:users"
    username: users
    password: users
    #jndi-name: # For JNDI lookup (class, url, username & password are ignored when set)
    #max-active:100 # Advanced configuration...
    #max-idle:8
    #min-idle:8
    #initial-size:10
    #validation-query:

  logging:
    level:
      org.springframework.security: DEBUG
  security:
    sessions: ALWAYS

server:
  port: 8081

  

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
